/* (c) 2014 LinkedIn Corp. All rights reserved.
 * 
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not use
 * this file except in compliance with the License. You may obtain a copy of the
 * License at  http://www.apache.org/licenses/LICENSE-2.0
 * 
 * Unless required by applicable law or agreed to in writing, software distributed
 * under the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR
 * CONDITIONS OF ANY KIND, either express or implied.
 */

package com.linkedin.cubert.block;

import java.io.IOException;

import org.apache.pig.data.Tuple;
import org.codehaus.jackson.JsonNode;

import com.linkedin.cubert.operator.TupleOperator;

/**
 * A block that is backed by the data generated by a TupleOperator.
 * 
 * @author Maneesh Varshney
 * 
 */
public class TupleOperatorBlock implements Block
{
    protected TupleOperator operator;
    private final BlockProperties props;

    public TupleOperatorBlock(TupleOperator operator, BlockProperties props)
    {
        this.operator = operator;
        this.props = props;
    }

    @Override
    public void configure(JsonNode json)
    {

    }

    @Override
    public Tuple next() throws IOException,
            InterruptedException
    {
        return operator.next();
    }

    @Override
    public void rewind() throws IOException
    {
        // TODO Auto-generated method stub

    }

    @Override
    public BlockProperties getProperties()
    {
        return props;
    }

}
